# -*- coding: utf-8 -*-
"""movies-grades.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F5GXx3WfEmr-PEYEdUCT2ssKF7JH-it-

# ANALISANDO NOTAS EM GERAL
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

notas = pd.read_csv("ratings.csv")
notas.head()

notas.columns = ["usuarioId", "filmeId", "nota", "momento"]
notas.head()

#notas['nota'].unique()
#notas['nota'].value_counts()
notas.nota.unique()
notas.nota.value_counts()

notas.shape

notas.nota.mean()

notas.nota.median()

notas.nota.plot(kind='hist')
notas.nota.describe()

import seaborn as sns

sns.boxplot(notas.nota)

"""# ANALISANDO NOTAS ESPECIFICAS POR FILME"""

notas.query("filmeId==1")

#notas.nota.query("filmeId==1")nao funciona, nota tem que vir depois da query
notas.query("filmeId==1").nota

# Consulta de notas com a media dos filmes com ID 1
notas.query("filmeId==1").nota.mean()

# Consulta de notas com a media dos filmes com ID 1
notas.query("filmeId==2").nota.mean()

notas.head()

# a media por cada ID de filme, mas note que vai tirar a media de tudo, do usuario, da nota e do momento
notas.groupby("filmeId").mean()

notas.groupby("filmeId").nota.mean()
# notas.groupby("filmeId").mean()["nota"] tbm funciona como codigo

#guardando em uma variavel
medias_por_filme =  notas.groupby("filmeId").nota.mean()
medias_por_filme.head()

medias_por_filme.plot(kind="hist")

#usando seaborn
sns.boxplot(medias_por_filme)

medias_por_filme.describe()

#histograma no seaborn chama distplot
sns.distplot(medias_por_filme)

sns.distplot(medias_por_filme, bins = 5)

#Matplotlib
print(plt.hist(medias_por_filme))

plt.figure(figsize=(5,8))

sns.boxplot(y=medias_por_filme)